name: Mino Pipeline Example
on: 
  push:
    branches:
      - ActionsTraining

jobs:
  Print-something-in-Console:
    runs-on: ubuntu-latest
    steps:
      - name: Print the Name of the running Job
        run: echo "Job is ${{ job.name }}"
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Setup Node.Js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: echo "Node.Js Installed"
      - name: Run First Attempt Script from pakage.json
        run: npm run print-test
      - run: echo "🍏 This job's status is ${{ job.status }}."
      